version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/start-container.sh
      timeout: 300
      runas: root
  
  ApplicationStop:
    - location: scripts/stop-container.sh
      timeout: 300
      runas: root

# artifacts:
#   files:
#     - '**/*'
#   base-directory: ../aws-cicd-on-flask-app
      